### ISSUE TITLE
Лаб7 

### ISSUE THREAD

**Issue by PatseiBSTU** [Liemrist/waddle#6]
Не нашла вызова calculation для StackU

**Comment by Liemrist** [comment]
Совсем не понимаю, как впихнуть в шаблон глобальной функции, где используются только типы int, double и подобные, проверку с каким-либо полем пользовательского класса.

**Comment by PatseiBSTU** [comment]
1)  оставить шаблон  - только возврат тип заменить 
 template<typename type> type calculation(int n, Stack<type>& stack) 
 в классе unit дописать оператор сравнения с интом
2) можно сравнивать unit c unitoм. Тогда тип n  меняем на type  и дописываем сравнение <  unit c unit  в классе unit.

**Comment by PatseiBSTU** [comment]
if (a > n)   - чтобы работала

**Comment by Liemrist** [comment]
Спасибо :)

**Comment by Liemrist** [comment]
Всё сделал.
